# Generated by Django 2.0.6 on 2018-11-27 09:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Model',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('model_name', models.CharField(max_length=120)),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Brand')),
            ],
        ),
    ]
