# Generated by Django 2.0.6 on 2018-11-27 10:17

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0002_model'),
    ]

    operations = [
        migrations.CreateModel(
            name='Vehicle',
            fields=[
                ('id', models.AutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('register_no', models.CharField(max_length=120)),
                ('value', models.DecimalField(decimal_places=2, max_digits=15)),
                ('date', models.DateTimeField()),
                ('brand_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Brand')),
                ('model_name', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='vehicle.Model')),
            ],
        ),
    ]
