# Generated by Django 2.0.6 on 2018-11-29 04:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('vehicle', '0004_vehicletest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='vehicle',
            name='date',
            field=models.DateField(),
        ),
    ]
